config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  resource :game, only: [:new, :create]
  # Defines the root path route ("/")
  root "games#new"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/character.rb
class Character
  attr_reader :name
  attr_reader :energy

  def initialize(number, energy=100)
    @name = "#{base_name} #{number}"
    @energy = energy
  end

  def dead?
    @energy <= 0
  end

  def alive?
    !dead?
  end

  def take_damage(amount)
    @energy -= amount
    @energy = 0 if dead?
    amount
  end

  def make_damage(to_character, amount)
    to_character.take_damage(amount)
  end

  private

  def base_name
    "Character"
  end
end

app/models/game.rb
class Game
  attr_reader :character_number
  attr_reader :turn_direction
  attr_reader :attack_direction
  attr_reader :characters
  attr_reader :chronicles

  def initialize(character_number, witches_percentage: 0, turn_direction: -1, attack_direction: -1)
    raise ArgumentError.new("this game is not fun - character_number must be greater than 1") if character_number <= 1
    @character_number = character_number.to_i
    # validate and store directions
    @turn_direction = valid_direction(turn_direction)
    @attack_direction = valid_direction(attack_direction)
    # validate witches percentage
    @witches_percentage = witches_percentage.to_f.clamp(0, 100)
    # generate a list of characters
    @characters = new_character_list(
      Witch => @witches_percentage / 100.0,
      Knight => (100 - @witches_percentage) / 100.0,
    )
    # grant the right of move to the first characte
    @current_acting_character_index = alive_character_ids.first
    # initialize the moves counter
    @chronicles = []
  end

  def finished?
    # is there more than one character left alive?
    alive_character_ids.size == 1
  end

  def play!
    while !finished?
      next_move!
    end
    winner
  end

  def winner
    raise "The game needs to be played first" unless finished?
    @characters[alive_character_ids.last]
  end

  def current_acting_character
    @characters[@current_acting_character_index]
  end

  private

  def valid_direction(direction)
    return 1 if direction > 0
    return -1 if direction < 0
    return 0
  end

  def new_character_list(desired_ratio)
    desired_ratio.reject!{|_, value| value == 0}
    tally = desired_ratio.transform_values { |_| 0}

    Array.new(@character_number) do |i|
      next_character_class = character_class_from_ratio(desired_ratio, tally)
      tally[next_character_class] += 1
      next_character_class.new(tally[next_character_class])
    end
  end

  def character_class_from_ratio(desired_ratio, current_tally)
    sum = hash_total(current_tally)
    current_ratio = tally_to_ratio(current_tally)
    pending_ratio = desired_ratio.merge(current_ratio) { |_, old_value, new_value| old_value - new_value }
    pending_ratio.max_by{|_, value| value}.first
  end

  def tally_to_ratio(tally)
    sum = hash_total(tally)
    if sum > 0
      return tally.transform_values { |value| value.to_f / sum }
    else
      return tally.transform_values { |_| 0 }
    end
  end

  def hash_total(hash)
    hash.values.sum
  end

  def next_move!
    attacker = current_acting_character
    target = closest_alive_character(@attack_direction)

    # roll the dice
    dice = rand(1..6)

    chronicles_entry = {
      current_acting_character_index: @current_acting_character_index,
      current_acting_character: attacker.name,
      text: ["#{current_acting_character.name} is active"],
      dice: dice,
      target: target.name,
    }

    # do the damage
    damage_part = make_damage(target, dice)
    chronicles_entry.merge! damage_part

    chronicles_entry[:text] << "#{attacker.name} attacks #{target.name} with #{chronicles_entry[:damage]} damage"
    if chronicles_entry[:target_dead]
      chronicles_entry[:text] << "#{target.name} is dead"
    else
      chronicles_entry[:text] << "#{target.name} has #{target.energy} energy left now"
    end

    puts chronicles_entry[:text].join("\n")
    @chronicles << chronicles_entry

    advance_turn!

    chronicles_entry
  end

  def make_damage(target, amount)
    scroll_entry_part = {}
    attacker = current_acting_character
    scroll_entry_part[:damage] = current_acting_character.make_damage(target, amount)
    if target.dead?
      scroll_entry_part[:target_dead] = true
    end

    scroll_entry_part
  end

  def advance_turn!
    if @turn_direction == 0
      @current_acting_character_index = alive_character_ids.excluding(@current_acting_character_index).sample
    else
      # advance the turn to the closest alive character
      @current_acting_character_index = closest_alive_character_id(@turn_direction)
    end
  end

  def alive_character_ids
    @characters.enum_for(:each_with_index).select{|character, index| character.alive?}.map{|character, id| id}
  end

  def closest_alive_character_id(direction = 1)
    direction = random_direction if direction == 0
    # from the alive character ids choose the next or previous
    new_id_index = (alive_character_ids.find_index(@current_acting_character_index) + direction) % alive_character_ids.size
    # that was an index in array of indexes, too meta
    alive_character_ids[new_id_index]
  end

  # returns 1 or -1 at random
  def random_direction
    (rand(0..1) * 2) - 1
  end

  def closest_alive_character(direction)
    @characters[closest_alive_character_id(direction)]
  end
end

app/models/knight.rb
class Knight < Character
  private
  def base_name
    "Knight"
  end
end

app/models/witch.rb
class Witch < Character
  def initialize(id, energy = 50)
    super(id, energy)
  end

  def make_damage(target, dice_value)
    dice_value *= 2 if target.instance_of?(Knight)
    super(target, dice_value)
  end

  private

  def base_name
    "Witch"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def new
    @page_title = "Start new Game of Knights"
  end
  
  def create
    @game = Game.new(
      params[:character_number].to_i,
      turn_direction: params[:turn_direction].to_i,
      attack_direction: params[:attack_direction].to_i,
      witches_percentage: params[:witches_percentage].to_i,
    )
    @game.play!
    @page_title = "Game of #{@game.character_number} Knights"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def page_title
    @page_title ||= 'Game of Knights'
  end
end

app/helpers/games_helper.rb
module GamesHelper
  def direction_description(direction)
    return 'previous' if direction == -1
    return 'next' if direction == 1
    return 'random'
  end
end

app/views/games/create.html.erb
<h1>A game of knights</h1>
<p>Settings:
  <ol>
    <li>Right of next turn passes to <%= direction_description(@game.turn_direction)%> character</li>
    <li>Attack goes against <%= direction_description(@game.attack_direction)%> character</li>
  </ol>
</p>
<p>
  Characters:
  <ul>
    <% @game.characters.each do |character| %>
      <li><%= character.name %></li>
    <% end %>
  </ul>
</p>
<p>
  <pre>
<%- @game.chronicles.each do |entry| %>
<%= entry[:text].join("\r\n") %>
<%- end %>
  </pre>
</pre>
<p><%= @game.winner.name%> won in <%= @game.chronicles.length %> moves!</p>
<p><a href="<%= root_path%>"><button>Start another one</button></a></p>

app/views/games/new.html.erb
<h1>Start a new game of knights:</h1>
<%= form_with url: game_url, method: :post, data: {turbo: false} do %>
  <p>
    <label>
      <span class="label">How many characters?:</span>
      <span class="control">
        <input name="character_number" type="number" min="2" max="20" step="1" value="10">
      </span>
    </label>
  </p>
  <p>
    <label>
      <span class="label">% of witches:</span>
      <span class="control">
        <input name="witches_percentage" type="number" min="0" max="100" step="1" value="0">
      </span>
    </label>
  </p>
  <p>
    <label>
      <span class="label">Right of next turn should pass to:</span>
      <span class="control">
        <input name="turn_direction" type="range" min="-1" max="1" step="1" datalist="turn_direction" value="-1">
        <datalist id="turn_direction">
          <option value="-1">Previous</option>
          <option value="0">Random</option>
          <option value="1">Next</option>
        </datalist>
    </label>
  </p>
  <p>
    <label>
      <span class="label">Attack goes against:</span>
      <span class="control">
        <input name="attack_direction" type="range" min="-1" max="1" step="1" datalist="attack_direction" value="-1">
        <datalist id="attack_direction">
          <option value="-1">Previous</option>
          <option value="0">Random</option>
          <option value="1">Next</option>
        </datalist>
    </label>
  </p>
  <p>
    <%= submit_tag "Play!" %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= page_title %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>